### ISSUE TITLE
Comment highlight

### ISSUE THREAD

**Issue by Masterquiz** [dzaima/paste#2]
There's a bug in the highlight syntax for APL about the comment lines. [Here](https://dzaima.github.io/paste#0U1AAAU1XF4WCzGSFR71zFUIyMosVgChRITk/Nzc1r4QLrEQhtqg0ryQzN1VBN1lB3VDbUF1B3UjbSB2sxzGnOF@hBKgRqhbFnDyF1NyCkkqFnMy8VKg8UCOamvySjNQimI0A#APL)'s a link for the ones I found.

**Comment by dzaima** [comment]
I intentionally parse lines beginning with `)`/`]` differently, but i guess it makes sense adding comment syntax for them
